#!/bin/sh
#
# @name HU Robosub UUV (Unmanned Underwater Vehicle)
#
# @type Vectored 6 DOF UUV
# @class Underwater Robot
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#

. ${R}etc/init.d/rc.uuv_defaults

param set-default SER_TEL1_BAUD 115200

param set-default CA_AIRFRAME 7

param set-default CA_ROTOR_COUNT 7
param set-default CA_R_REV 255

param set-default CA_ROTOR0_AX 0
param set-default CA_ROTOR0_AY 1
param set-default CA_ROTOR0_AZ 0
param set-default CA_ROTOR0_KM 0
param set-default CA_ROTOR0_PX -1
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ 0

# Stern vertical (2)
param set-default CA_ROTOR1_AX 0
param set-default CA_ROTOR1_AY 0
param set-default CA_ROTOR1_AZ -1
param set-default CA_ROTOR1_KM 0
param set-default CA_ROTOR1_PX 0
param set-default CA_ROTOR1_PY -1
param set-default CA_ROTOR1_PZ 0

# Bow starboard vertical (3)
param set-default CA_ROTOR2_AX 0
param set-default CA_ROTOR2_AY 0
param set-default CA_ROTOR2_AZ -1
param set-default CA_ROTOR2_PX 0.3
param set-default CA_ROTOR2_PY 1
param set-default CA_ROTOR2_PZ 0
# Limit thrust output to 70 percent for vertical bow thrusters
param set-default CA_ROTOR2_CT 0.7

# Bow port vertical (4)
param set-default CA_ROTOR3_AX 0
param set-default CA_ROTOR3_AY 0
param set-default CA_ROTOR3_AZ -1
param set-default CA_ROTOR3_PX -0.3
param set-default CA_ROTOR3_PY 1
param set-default CA_ROTOR3_PZ 0
# Limit thrust output to 70 percent for vertical bow thrusters
param set-default CA_ROTOR3_CT 0.7

# Bow horizontal (5)
param set-default CA_ROTOR4_AX 1
param set-default CA_ROTOR4_AY 0
param set-default CA_ROTOR4_AZ 0
param set-default CA_ROTOR4_PX 0
param set-default CA_ROTOR4_PY 0.5
param set-default CA_ROTOR4_PZ 0

# T200 starboard horizontal (6)
param set-default CA_ROTOR5_AX 0
param set-default CA_ROTOR5_AY 1
param set-default CA_ROTOR5_AZ 0
param set-default CA_ROTOR5_KM 0
param set-default CA_ROTOR5_PX 1
param set-default CA_ROTOR5_PY 0
param set-default CA_ROTOR5_PZ 0

# Stern horizontal (7)
param set-default CA_ROTOR6_AX 1
param set-default CA_ROTOR6_AY 0
param set-default CA_ROTOR6_AZ 0
param set-default CA_ROTOR6_PX 0
param set-default CA_ROTOR6_PY -0.8
param set-default CA_ROTOR6_PZ 0

# param set-default PWM_AUX_OUT 1234567  # Enable channels 1-7 for PWM
param set-default PWM_MAIN_TIM0 400
param set-default PWM_MAIN_TIM1 400
param set-default PWM_MAIN_TIM2 400
param set-default PWM_MAIN_DIS0 1500
param set-default PWM_MAIN_MIN0 1100
param set-default PWM_MAIN_MAX0 1900
param set-default PWM_MAIN_DIS1 1500
param set-default PWM_MAIN_MIN1 1100
param set-default PWM_MAIN_MAX1 1900
param set-default PWM_MAIN_DIS2 1500
param set-default PWM_MAIN_MIN2 1100
param set-default PWM_MAIN_MAX2 1900
param set-default PWM_MAIN_DIS3 1500
param set-default PWM_MAIN_MIN3 1100
param set-default PWM_MAIN_MAX3 1900
param set-default PWM_MAIN_DIS4 1500
param set-default PWM_MAIN_MIN4 1100
param set-default PWM_MAIN_MAX4 1900
param set-default PWM_MAIN_DIS5 1500
param set-default PWM_MAIN_MIN5 1100
param set-default PWM_MAIN_MAX5 1900
param set-default PWM_MAIN_DIS6 1500
param set-default PWM_MAIN_MIN6 1100
param set-default PWM_MAIN_MAX6 1900
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 106
param set-default PWM_MAIN_FUNC7 107

param set-default EKF2_EV_CTRL 4

param set-default UXRCE_DDS_CFG 1
param set-default UXRCE_DDS_AG_IP -1856423239
param set-default UXRCE_DDS_PRT 8888

param set-default SENS_EN_INA228 1

param set-default BAT1_N_CELLS 3
param set-default BAT1_SOURCE 0

param set-default MAV_0_CONFIG 0
param set-default MAV_1_CONFIG 103
param set-default MAV_1_RATE 40000
param set-default SER_TEL3_BAUD 115200

# rs_motor_control start
# rs_remote_control start
# control_allocator start # disabled for RAMI-2025
# land_detector start rover

# rs_canfd_socket start
# rs_canfd_receiver start
# rs_canfd_sender start

# rs_pos_control start # disabled for RAMI-2025
# rs_status_monitor start # disabled for RAMI-2025
